[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = [
  "pnpm install --frozen-lockfile",
  "cd apps/web"
]

[phases.build]
cmds = [
  "cd apps/web",
  "pnpm run build"
]

[start]
cmd = "cd apps/web && pnpm run start"
