name = "handywriterz-subpath-router"
main = "src/index.ts"
compatibility_date = "2024-09-02"

[vars]
# WEB_ORIGIN and MICROFEED_ORIGIN are provided at deploy-time via CI secrets

# Route this worker on the primary domain. Adjust if deploying to a different zone.
routes = [
	{ pattern = "handywriterz.com/*", zone_name = "handywriterz.com" }
]
