name = "strapi-webhooks"
main = "src/index.ts"
compatibility_date = "2025-06-17"

[env.production]
vars = { }

[env.production.vars]
CLOUDFLARE_ZONE_ID = ""
WEBHOOK_SECRET = ""

[[env.production.routes]]
pattern = "handywriterz.com/webhooks/*"
zone_name = "handywriterz.com"
