name = "strapi-scheduler"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Cron trigger - runs every 5 minutes to check for scheduled content
[triggers]
crons = ["*/5 * * * *"]

# Environment variables (set via wrangler secret or dashboard)
[vars]
# STRAPI_URL = "https://cms.handywriterz.com"

# Secrets (use `wrangler secret put <NAME>`)
# - STRAPI_API_TOKEN
# - MATTERMOST_WEBHOOK_URL (optional)
