name = "upload-broker"
main = "src/index.ts"
compatibility_date = "2025-06-17"

[vars]
S3_ENDPOINT = "https://your-account.r2.cloudflarestorage.com"
S3_REGION = "auto"
S3_BUCKET = "cms-media"
FORCE_PATH_STYLE = "true"
DOWNLOAD_TTL_SECONDS = "300"

[env.staging.vars]
S3_BUCKET = "cms-media-staging"

[env.production.vars]
S3_BUCKET = "cms-media"
