name: D1 Migrations (Microfeed)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment (preview or production)'
        required: true
        default: 'preview'
        type: choice
        options:
          - preview
          - production

jobs:
  migrate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      D1_DATABASE_NAME: ${{ secrets.D1_DATABASE_NAME }}
      TARGET_ENV: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install wrangler
        run: npm i -g wrangler@3

      - name: Run migrations (domains, posts, messaging, orders)
        run: |
          set -e
          if [ -z "$D1_DATABASE_NAME" ]; then echo "D1_DATABASE_NAME secret not set" && exit 1; fi
          wrangler d1 execute "$D1_DATABASE_NAME" --remote -e "$TARGET_ENV" --file apps/microfeed/ops/db/domains.sql
          wrangler d1 execute "$D1_DATABASE_NAME" --remote -e "$TARGET_ENV" --file apps/microfeed/ops/db/posts.sql
          wrangler d1 execute "$D1_DATABASE_NAME" --remote -e "$TARGET_ENV" --file apps/microfeed/ops/db/messaging.sql
          wrangler d1 execute "$D1_DATABASE_NAME" --remote -e "$TARGET_ENV" --file apps/microfeed/ops/db/orders.sql
